name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test,asimov]

    - name: Run tests
      run: |
        pytest --junitxml=test-results.xml --cov src --cov-report=xml --cov-report=html

  # publish:
  #   uses: microsoft/action-python/.github/workflows/publish.yml@0.6.4
  #   secrets:
  #     PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  #     TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
